### ISSUE TITLE
Sort of not running on macOS Sierra

### ISSUE THREAD

**Issue by johnsec23** [ali-rantakari/icalBuddy#16]
1st-Awesome tool. THX for making it free!

Since updating to Sierra when running I get an error and I do get the output as well. 
I pipe the results to a txt file, so I can email that to my wife, so I can't use the >/dev/null solution. 
If you are still supporting this and it is an easy fix I appreciate the help, IF NOT, I get it! Thanks a lot for having provided this!
Here is the output 

MacBook-Pro:mtgs-sms john$ /usr/local/bin/icalBuddy eventsToday
2016-10-14 09:25:32.619 icalBuddy[40228:3985212] Error loading /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation:  dlopen(/System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation, 265): no suitable image found.  Did find:
    /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation: mach-o, but wrong architecture
• Chiro (Home)
    9:20 AM - 10:20 AM

**Comment by trailgirl** [comment]
I have Sierra too. I'm using 2>/dev/null to redirect the errors:

/usr/local/bin/icalBuddy eventsToday >today.txt 2>/dev/null

**Comment by johnsec23** [comment]
YES! that worked. Thanks a lot!
