### ISSUE TITLE
Due date for uncompletedTasks doesn't contain a timestamp

### ISSUE THREAD

**Issue by Argon-** [ali-rantakari/icalBuddy#2]
Although such a value exists for reminders, the due date printed for e.g. `icalBuddy uncompletedTasks` doesn't contain a time value. 
Is there a reason for this behavior?

**Comment by ali-rantakari** [comment]
Seems to work for me. Do you mean that you see `due:` in the output, but no value for it?

**Comment by ali-rantakari** [comment]
Oh, now I understand — you mean that times are not shown, only dates. I can't remember the reason for this behavior, and I don't see why it couldn't be changed.

**Comment by ali-rantakari** [comment]
Fixed in v1.8.9

**Comment by Argon-** [comment]
Thanks a lot :)
