### ISSUE TITLE
"bad CPU type in executable"

### ISSUE THREAD

**Issue by jasonrwang** [ali-rantakari/icalBuddy#25]
Hi, I wonder if I'm seeing an issue similar to #24 at some layer. I'm running macOS Catalina on an i5-8259U. I installed icalBuddy but am running into an issue trying to call it in Terminal and iTerm:

```
zsh: bad CPU type in executable: icalBuddy
```

I looked a bit through Console and can't seem to spot anything for icalBuddy. Maybe I'm looking in the wrong place?

**Comment by MattiSG** [comment]
See https://github.com/ali-rantakari/icalBuddy/pull/23.
