### ISSUE TITLE
icalBuddy not working in Yosemite

### ISSUE THREAD

**Issue by AmaruCoder** [ali-rantakari/icalBuddy#6]
I upgraded OS X to Yosemite, and now I get the following error message when I try to run icalBuddy:

2014-10-18 12:03:05.666 icalBuddy[46273:103577] Error loading /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation:  dlopen(/System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation, 265): no suitable image found.  Did find:
    /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation: mach-o, but wrong architecture

**Comment by ali-rantakari** [comment]
This is because your icalBuddy installation is an i386 binary, and in Yosemite CalendarFoundation seems to only exist for the x86_64 architecture.

You can fix this by reinstalling icalBuddy from Homebrew:

```
rm /usr/local/bin/icalBuddy
rm /usr/local/share/man/man1/icalBuddy*
brew install ical-buddy
```

**Comment by AmaruCoder** [comment]
Thank you. This solved my issue.

**Comment by arthurguillemot** [comment]
Hi ! 

Is there an other way to do it ? I don't want to uninstall macports...

Thanks !
